server:
  port: 7002


eureka:
  instance:
    hostname: eureka7002.com:7002
  client:
    register-with-eureka: false # 设置是否将自己作为客户端注册到注册中心（默认true）
    fetch-registry: false # 设置是否从注册中心获取注册信息（默认true）
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7003.com:7003/eureka/         # 集群
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/        单机配置

